# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1511416149);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1511416118);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 58);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1511395200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1511416168);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1511416140399");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1511417948399");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1511416121791");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1511419721791");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20171115095126");
user_pref("browser.slowStartup.averageTime", 965);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20171115095126");
user_pref("browser.startup.homepage_override.mstone", "57.0");
user_pref("browser.tabs.remote.autostart.2", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":12,\"newElementCount\":2}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20171123);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1511416120568");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "optedOut");
user_pref("e10s.rollout.cohortSample", "0.177569");
user_pref("e10s.rollout.cohortSample.multi", "0.636215");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.formautofill.available", "off");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20171115095126");
user_pref("extensions.lastAppVersion", "57.0");
user_pref("extensions.lastPlatformVersion", "57.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.extensions.formautofill.available", "off");
user_pref("extensions.shield-recipe-client.user_id", "64d59a6c-a6a1-4b2d-9b2f-45b5126c0fbc");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"410059f7-f838-49a5-97c4-954bb5467ac6\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1511416275);
user_pref("toolkit.telemetry.cachedClientID", "12072f7a-8b47-4840-973a-0a25658c8e31");
user_pref("toolkit.telemetry.previousBuildID", "20171115095126");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
